/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as Errors503RouteImport } from './routes/errors/503'
import { Route as Errors500RouteImport } from './routes/errors/500'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as Errors403RouteImport } from './routes/errors/403'
import { Route as Errors401RouteImport } from './routes/errors/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSystemUsersRouteImport } from './routes/_authenticated/system/users'
import { Route as AuthenticatedSystemRolesRouteImport } from './routes/_authenticated/system/roles'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Errors503Route = Errors503RouteImport.update({
  id: '/errors/503',
  path: '/errors/503',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors401Route = Errors401RouteImport.update({
  id: '/errors/401',
  path: '/errors/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedSystemUsersRoute =
  AuthenticatedSystemUsersRouteImport.update({
    id: '/system/users',
    path: '/system/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRolesRoute =
  AuthenticatedSystemRolesRouteImport.update({
    id: '/system/roles',
    path: '/system/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/system/roles': typeof AuthenticatedSystemRolesRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/system/roles': typeof AuthenticatedSystemRolesRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/system/roles': typeof AuthenticatedSystemRolesRoute
  '/_authenticated/system/users': typeof AuthenticatedSystemUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/system/roles'
    | '/system/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/'
    | '/system/roles'
    | '/system/users'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/_authenticated/'
    | '/_authenticated/system/roles'
    | '/_authenticated/system/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Errors401Route: typeof Errors401Route
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
  Errors503Route: typeof Errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/errors/503': {
      id: '/errors/503'
      path: '/errors/503'
      fullPath: '/errors/503'
      preLoaderRoute: typeof Errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/401': {
      id: '/errors/401'
      path: '/errors/401'
      fullPath: '/errors/401'
      preLoaderRoute: typeof Errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/system/users': {
      id: '/_authenticated/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/roles': {
      id: '/_authenticated/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof AuthenticatedSystemRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSystemRolesRoute: typeof AuthenticatedSystemRolesRoute
  AuthenticatedSystemUsersRoute: typeof AuthenticatedSystemUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSystemRolesRoute: AuthenticatedSystemRolesRoute,
  AuthenticatedSystemUsersRoute: AuthenticatedSystemUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Errors401Route: Errors401Route,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
  Errors503Route: Errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
