/** Outline 后处理单次选中上限，超出部分忽略 */
export const MAX_BIM_SELECTION = 200

export const IFC_TYPE_MAP = {
  IfcProject: { value: 'IfcProject', label: '项目' },
  IfcBeam: { value: 'IfcBeam', label: '梁' },
  IfcBeamStandardCase: { value: 'IfcBeamStandardCase', label: '标准光束' },
  IfcBuilding: { value: 'IfcBuilding', label: '建筑' },
  IfcBuildingElement: { value: 'IfcBuildingElement', label: '建筑构件' },
  IfcBuildingElementPart: { value: 'IfcBuildingElementPart', label: '建筑构件部分' },
  IfcBuildingElementProxy: { value: 'IfcBuildingElementProxy', label: '建筑构件代替物' },
  IfcBuildingStorey: { value: 'IfcBuildingStorey', label: '建筑楼层' },
  IfcColumn: { value: 'IfcColumn', label: '柱' },
  IfcColumnStandardCase: { value: 'IfcColumnStandardCase', label: '标准栏目' },
  IfcCovering: { value: 'IfcCovering', label: '面层' },
  IfcCurtainWall: { value: 'IfcCurtainWall', label: '幕墙' },
  IfcDoor: { value: 'IfcDoor', label: '门' },
  IfcDoorStandardCase: { value: 'IfcDoorStandardCase', label: '标准门' },
  IfcElement: { value: 'IfcElement', label: '构件' },
  IfcElementAssembly: { value: 'IfcElementAssembly', label: '构件组装' },
  IfcElementComponent: { value: 'IfcElementComponent', label: '构件组件' },
  IfcFooting: { value: 'IfcFooting', label: '基础' },
  IfcFurnishingElement: { value: 'IfcFurnishingElement', label: '装饰构件' },
  IfcGrid: { value: 'IfcGrid', label: '网格' },
  IfcMaterial: { value: 'IfcMaterial', label: '材料' },
  IfcMaterialLayer: { value: 'IfcMaterialLayer', label: '材料层' },
  IfcMechanicalFastener: { value: 'IfcMechanicalFastener', label: '机械紧固件' },
  IfcMember: { value: 'IfcMember', label: '成员' },
  IfcMemberStandardCase: { value: 'IfcMemberStandardCase', label: '标准元素' },
  IfcOpeningElement: { value: 'IfcOpeningElement', label: '孔口' },
  IfcOpeningStandardCase: { value: 'IfcOpeningStandardCase', label: '孔口2' },
  IfcPile: { value: 'IfcPile', label: '桩' },
  IfcPlate: { value: 'IfcPlate', label: '板' },
  IfcPlateStandardCase: { value: 'IfcPlateStandardCase', label: '薄标准板' },
  IfcPresentationLayerAssignment: { value: 'IfcPresentationLayerAssignment', label: '层' },
  IfcRailing: { value: 'IfcRailing', label: '栏杆' },
  IfcRamp: { value: 'IfcRamp', label: '坡道' },
  IfcRampFlight: { value: 'IfcRampFlight', label: '坡道楼梯' },
  IfcReinforcingBar: { value: 'IfcReinforcingBar', label: '加强筋' },
  IfcReinforcingElement: { value: 'IfcReinforcingElement', label: '加强构件' },
  IfcReinforcingMesh: { value: 'IfcReinforcingMesh', label: '加强网' },
  IfcSite: { value: 'IfcSite', label: '场所' },
  IfcRoof: { value: 'IfcRoof', label: '屋顶' },
  IfcSlab: { value: 'IfcSlab', label: '平板' },
  IfcSlabStandardCase: { value: 'IfcSlabStandardCase', label: '标准板' },
  IfcSpace: { value: 'IfcSpace', label: '空间' },
  IfcStair: { value: 'IfcStair', label: '楼梯' },
  IfcStairFlight: { value: 'IfcStairFlight', label: '单段梯' },
  IfcWall: { value: 'IfcWall', label: '墙' },
  IfcWallStandardCase: { value: 'IfcWallStandardCase', label: '标准墙' },
  IfcWindow: { value: 'IfcWindow', label: '窗' },
  IfcWindowStandardCase: { value: 'IfcWindowStandardCase', label: '标准窗口' },
  IfcZone: { value: 'IfcZone', label: '区域' }
} as const

export type IfcType = keyof typeof IFC_TYPE_MAP
