import { randomUUID } from 'node:crypto'

import {
  CallHandler,
  ExecutionContext,
  HttpStatus,
  Injectable,
  NestInterceptor
} from '@nestjs/common'
import { Reflector } from '@nestjs/core'
import { Observable } from 'rxjs'

import { map } from 'rxjs/operators'

import { BYPASS_TRANSFORM_KEY } from '../decorators/bypass-transform.decorator'

import type { ApiResponse } from '../interfaces/api-response.interface'

type HttpRequest = {
  id?: string
  headers: Record<string, string | string[] | undefined>
}

type HttpResponse = {
  statusCode?: number
}

@Injectable()
export class TransformInterceptor<T> implements NestInterceptor<T, ApiResponse<T>> {
  constructor(private readonly reflector: Reflector) {}

  intercept(context: ExecutionContext, next: CallHandler): Observable<ApiResponse<T>> {
    const bypass = this.reflector.getAllAndOverride<boolean>(BYPASS_TRANSFORM_KEY, [
      context.getHandler(),
      context.getClass()
    ])

    if (bypass) {
      return next.handle()
    }

    const http = context.switchToHttp()
    const request = http.getRequest<HttpRequest>()
    const response = http.getResponse<HttpResponse>()
    // Use the ID generated by pino-http (nestjs-pino)
    const requestIdHeader = request.headers['x-request-id']
    const requestId =
      request.id ||
      (Array.isArray(requestIdHeader) ? requestIdHeader[0] : requestIdHeader) ||
      randomUUID()
    // Ensure requestId is available if not already set
    if (!request.id) {
      request.id = requestId
    }

    return next.handle().pipe(
      map((data) => ({
        code: response.statusCode || HttpStatus.OK,
        message: 'Success',
        data,
        requestId,
        timestamp: new Date().toISOString()
      }))
    )
  }
}
