import {
  ACCESS_TOKEN_CONFIGURABLE_KEY,
  ACTIVE_AGENT_PLUGINS_CONFIGURABLE_KEY,
  AGENT_APPROVAL_ID_CONFIGURABLE_KEY,
  AGENT_LOCALE_CONFIGURABLE_KEY,
  AGENT_MEMORY_CONFIGURABLE_KEY,
  AGENT_MODEL_METADATA_CONFIGURABLE_KEY,
  AGENT_PERMISSIONS_CONFIGURABLE_KEY,
  AGENT_RUN_ID_CONFIGURABLE_KEY,
  AGENT_STEP_UP_TOKEN_CONFIGURABLE_KEY,
  AGENT_TENANT_ID_CONFIGURABLE_KEY,
  AGENT_THREAD_ID_CONFIGURABLE_KEY,
  AGENT_TOOL_NAME_CONFIGURABLE_KEY,
  AGENT_TRACE_ID_CONFIGURABLE_KEY,
  AGENT_USER_ID_CONFIGURABLE_KEY,
  agentModelMetadataSchema
} from '@zen/shared'
import { z } from 'zod'

export const ContextSchema = z.object({
  [ACCESS_TOKEN_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_TENANT_ID_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_USER_ID_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_THREAD_ID_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_RUN_ID_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_TRACE_ID_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_LOCALE_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_PERMISSIONS_CONFIGURABLE_KEY]: z.array(z.string()).default([]),
  [AGENT_MODEL_METADATA_CONFIGURABLE_KEY]: agentModelMetadataSchema.optional(),
  [AGENT_MEMORY_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_STEP_UP_TOKEN_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_APPROVAL_ID_CONFIGURABLE_KEY]: z.string().optional(),
  [AGENT_TOOL_NAME_CONFIGURABLE_KEY]: z.string().optional(),
  [ACTIVE_AGENT_PLUGINS_CONFIGURABLE_KEY]: z.array(z.string()).default([])
})
