ALTER TYPE "Gender" RENAME VALUE 'MALE' TO 'male';
ALTER TYPE "Gender" RENAME VALUE 'FEMALE' TO 'female';
ALTER TYPE "Gender" RENAME VALUE 'UNKNOWN' TO 'unknown';

ALTER TYPE "MfaType" RENAME VALUE 'TOTP' TO 'totp';
ALTER TYPE "MfaType" RENAME VALUE 'SMS' TO 'sms';
ALTER TYPE "MfaType" RENAME VALUE 'EMAIL' TO 'email';
ALTER TYPE "MfaType" RENAME VALUE 'OFF' TO 'off';

ALTER TYPE "Theme" RENAME VALUE 'LIGHT' TO 'light';
ALTER TYPE "Theme" RENAME VALUE 'DARK' TO 'dark';
ALTER TYPE "Theme" RENAME VALUE 'SYSTEM' TO 'system';

ALTER TYPE "RecordStatus" RENAME VALUE 'ACTIVE' TO 'active';
ALTER TYPE "RecordStatus" RENAME VALUE 'DISABLED' TO 'disabled';
